export const UserConstant = {
    SET_USER : "SET_USER",
    LOGOUT_USER : "LOGOUT_USER",
    EDIT_USER : "EDIT_USER",
    SET_LOADING:'SET_LOADING',
    SET_ERRORS:'SET_ERRORS',
    GET_ALL_CLINICS : 'GET_ALL_CLINICS',
    ADD_CLINIC: 'ADD_CLINIC',
    ADD_STAFF:'ADD_STAFF',
    GET_ALL_USERS:'GET_ALL_USERS',
    GET_BOOKING_USER:'GET_BOOKING_USER',
    GET_ALL_REPORTS:'GET_ALL_REPORTS'
  }
  
  